// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFDyG_XyOGVR9i9YdGD1s3-iLt5STs24E',
    appId: '1:154826302240:web:00ef72968ac719b2342d45',
    messagingSenderId: '154826302240',
    projectId: 'studyflow-44f9c',
    authDomain: 'studyflow-44f9c.firebaseapp.com',
    storageBucket: 'studyflow-44f9c.firebasestorage.app',
    measurementId: 'G-4S0NFBD51V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxWC4vSK9UlTLJdVTCIxFF6Rmm_yJO4_s',
    appId: '1:154826302240:android:e151acd649665387342d45',
    messagingSenderId: '154826302240',
    projectId: 'studyflow-44f9c',
    storageBucket: 'studyflow-44f9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKXFAo_7yj6XuHvOyfekb_5C_TVmCgd7w',
    appId: '1:154826302240:ios:58dcbcbe152d2517342d45',
    messagingSenderId: '154826302240',
    projectId: 'studyflow-44f9c',
    storageBucket: 'studyflow-44f9c.firebasestorage.app',
    iosBundleId: 'com.example.studyFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKXFAo_7yj6XuHvOyfekb_5C_TVmCgd7w',
    appId: '1:154826302240:ios:58dcbcbe152d2517342d45',
    messagingSenderId: '154826302240',
    projectId: 'studyflow-44f9c',
    storageBucket: 'studyflow-44f9c.firebasestorage.app',
    iosBundleId: 'com.example.studyFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFDyG_XyOGVR9i9YdGD1s3-iLt5STs24E',
    appId: '1:154826302240:web:a3979d8f45369784342d45',
    messagingSenderId: '154826302240',
    projectId: 'studyflow-44f9c',
    authDomain: 'studyflow-44f9c.firebaseapp.com',
    storageBucket: 'studyflow-44f9c.firebasestorage.app',
    measurementId: 'G-0W9B4CLK0S',
  );
}
