enum TextosAplicacao {
  tituloApp('StudyFlow'),

  textoBemVindo('Organize seus estudos com foco e disciplina'),

  progressoTitulo('Acompanhe seu progresso'),
  progressoSubtitulo('Estatísticas e gráficos em tempo real'),

  pomodoroTitulo('Timer Pomodoro'),
  pomodoroSubtitulo('Técnica comprovada de foco'),

  definaMetasTitulo('Defina metas'),
  definaMetasSubtitulo('Organize seus objetivos de estudo'),

  comecarAgora('Começar Agora'),
  jaTenhoConta('Já tenho conta'),

  textoRodape(
    'Junte-se a milhares de estudantes que já transformaram sua rotina de estudos',
  ),

  loginTitulo('Bem-vindo de volta!'),
  loginSubtitulo('Entre para continuar seus estudos'),
  loginRotuloEmail('Email'),
  loginDicaEmail('seu@email.com'),
  loginRotuloSenha('Senha'),
  loginDicaSenha('Digite sua senha'),
  loginEsqueceuSenha('Esqueceu sua senha?'),
  loginBotaoConfirmar('Entrar'),
  loginOuContinueCom('ou continue com'),
  loginSemContaPrefixo('Não tem conta? '),
  loginCadastrese('Cadastre-se'),
  cadastroTitulo('Crie sua conta'),
  cadastroSubtitulo('Comece sua jornada de estudos agora'),
  cadastroRotuloNome('Nome Completo'),
  cadastroDicaNome('Seu nome'),
  cadastroRotuloEmail('Email'),
  cadastroDicaEmail('seu@email.com'),
  cadastroRotuloSenha('Senha'),
  cadastroDicaSenha('Mínimo 6 caracteres'),
  cadastroRotuloConfirmarSenha('Confirmar Senha'),
  cadastroDicaConfirmarSenha('Digite a senha novamente'),
  cadastroAceiteTermosPrefixo('Aceito os '),
  cadastroTermosUso('Termos de Uso'),
  cadastroAceiteTermosMeio(' e a '),
  cadastroPoliticaPrivacidade('Política de Privacidade'),
  cadastroBotaoConfirmar('Criar Conta'),
  cadastroJaTemContaPrefixo('Já tem uma conta? '),
  cadastroFazerLogin('Fazer login'),
  cadastroAvisoLegalPrefixo('Ao criar uma conta, você concorda com nossos '),
  cadastroAvisoLegalMeio(' e '),
  funcionalidadeEmBreve('Esta função ainda será implementada.'),

  dashboardHoje('Hoje'),
  dashboardTempoEstudadoRotulo('Tempo estudado'),
  dashboardSessoesConcluidasRotulo('Sessões concluídas'),
  dashboardSequenciaRotulo('Sequência atual'),
  dashboardProgressoSemanal('Progresso Semanal'),
  dashboardIniciarSessao('Iniciar Sessão de Estudo'),
  dashboardTotalEstudadoRotulo('Total estudado'),
  dashboardMetasRotulo('Metas'),
  dashboardMateriasRotulo('Matérias'),
  dashboardSessoesRotulo('Sessões'),
  dashboardProximaMeta('Próxima meta'),
  dashboardVer('Ver'),
  materiasTitulo('Minhas Matérias'),
  materiasSubtituloSingular('1 matéria cadastrada'),
  materiasSubtituloPlural('matérias cadastradas'),
  materiasHorasEstudadas(' horas estudadas'),
  materiasProgresso('Progresso'),
  materiasDialogoNova('Nova Matéria'),
  materiasDialogoEditar('Editar Matéria'),
  materiasRotuloNome('Nome da matéria'),
  materiasDicaNome('Ex: Álgebra Linear'),
  materiasRotuloProgresso('Progresso (%)'),
  materiasCancelar('Cancelar'),
  materiasAdicionar('Adicionar'),
  materiasSalvar('Salvar'),
  materiasErroCarregar(
    'Não foi possível carregar suas matérias. Tente novamente.',
  ),
  perfilTitulo('Perfil & Metas'),
  perfilSubtitulo('Defina e acompanhe seus objetivos'),
  perfilConfiguracoes('Configurações'),
  perfilConfiguracoesSub('Timer, notificações e mais'),
  perfilSairConta('Sair da conta'),
  perfilSairContaTitulo('Sair da conta?'),
  perfilSairContaMensagem(
    'Tem certeza que deseja sair? Você precisará entrar novamente.',
  ),
  perfilSairContaConfirmar('Sair'),
  perfilSairContaCancelar('Cancelar'),
  perfilConquistas('Conquistas'),
  perfilConquistaPrimeiraSessao('Primeira Sessão'),
  perfilConquistaDezHoras('10 Horas'),
  perfilConquistaSeteDias('7 Dias'),
  perfilMinhasMetas('Minhas Metas'),
  perfilNovaMeta('Nova Meta'),
  perfilNovaMetaTituloModal('Nova Meta'),
  perfilMetaTituloRotulo('Título da Meta'),
  perfilMetaTituloDica('Ex: Concluir curso de Álgebra'),
  perfilMetaDescricaoRotulo('Descrição'),
  perfilMetaDescricaoDica('Descreva sua meta...'),
  perfilMetaPrazoRotulo('Prazo'),
  perfilMetaPrazoDica('dd/mm/aaaa'),
  perfilMetaEtapasRotulo('Etapas'),
  perfilMetaEtapasDica('Adicionar etapas'),
  perfilNovaMetaCriar('Criar Meta'),
  perfilEditarMetaTituloModal('Editar Meta'),
  perfilMetaSalvar('Salvar'),
  perfilMetaSalva('Meta atualizada com sucesso.'),
  perfilMetaCriada('Meta criada com sucesso.'),
  perfilMetasAtivas('Metas Ativas'),
  perfilMetasConcluidas('Metas Concluídas'),
  perfilEditar('Editar'),
  perfilProgresso('Progresso'),
  perfilMarcarConcluida('Marcar como concluída'),
  perfilExcluir('Excluir'),
  perfilMetaConcluidaStatus('Concluída'),
  perfilRemover('Remover'),
  perfilErroCarregarMetas(
    'Não foi possível carregar suas metas. Verifique sua conexão e tente novamente.',
  );

  const TextosAplicacao(this.texto);
  final String texto;
}
